# Generated by Django 5.2.5 on 2025-08-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_novel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
    ]
