# Generated by Django 5.2.5 on 2025-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_novel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
