# Generated by Django 5.2.5 on 2025-09-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
