# Generated by Django 5.2.5 on 2025-08-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_genre_options_novel_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='genres',
            field=models.ManyToManyField(blank=True, to='main.genre'),
        ),
    ]
